package me.serce.bazillion

import com.intellij.openapi.externalSystem.service.settings.AbstractExternalSystemToolWindowCondition
import com.intellij.openapi.externalSystem.service.task.ui.AbstractExternalSystemToolWindowFactory

class BazilToolWindowFactory : AbstractExternalSystemToolWindowFactory(SYSTEM_ID)
class BazilToolWindowFactoryCondition : AbstractExternalSystemToolWindowCondition(SYSTEM_ID)
